CREATE TABLE users (
    users_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_email VARCHAR(255) NOT NULL,
    users_username VARCHAR(100) NOT NULL,
    users_mdp VARCHAR(255) NOT NULL,
    users_date_creation TIMESTAMP,
    users_nbVictoire INTEGER DEFAULT 0,
    users_elo INTEGER DEFAULT 200
);

CREATE TABLE joueur (
    joueur_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    joueur_numero INTEGER,
    joueur_nbPierre INTEGER DEFAULT 0,
    joueur_nbFeuille INTEGER DEFAULT 0,
    joueur_nbCiseau INTEGER DEFAULT 0,
    users_id INTEGER,
    FOREIGN KEY (users_id) REFERENCES users(users_id) ON DELETE CASCADE
);

CREATE TABLE partie (
    partie_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partie_code INTEGER,
    partie_plateau JSONB,
    partie_etat VARCHAR(15) CHECK (partie_etat IN ('TERMINEE', 'EN COURS', 'EN ATTENTE')),
    partie_joueurActif INTEGER,
    partie_date_creation TIMESTAMP,
    partie_date_modif TIMESTAMP,
    partie_joueurGagnant INTEGER,
    partie_tdj INTEGER,
    partie_public BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (partie_joueurGagnant) REFERENCES joueur(joueur_id) ON DELETE SET NULL
);

CREATE TABLE archive_partie (
    archive_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partie_id INTEGER NOT NULL,
    users_id INTEGER NOT NULL,
    users2_id INTEGER NOT NULL,
    username1 VARCHAR(100) NOT NULL,
    username2 VARCHAR(100) NOT NULL,
    date_creation TIMESTAMP,
    date_fin TIMESTAMP,
    gagnant BOOLEAN DEFAULT FALSE,
    public BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (partie_id) REFERENCES partie(partie_id) ON DELETE CASCADE,
    FOREIGN KEY (users_id) REFERENCES users(users_id) ON DELETE CASCADE,
    FOREIGN KEY (users2_id) REFERENCES users(users_id) ON DELETE CASCADE
);

CREATE TABLE archives_tourdejeu (
    tdj_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tdj_nTour INTEGER NOT NULL,
    tdj_joueurActif INTEGER NOT NULL,
    xDepart INTEGER NOT NULL,
    yDepart INTEGER NOT NULL,
    xArrive INTEGER NOT NULL,
    yArrive INTEGER NOT NULL,
    tdj_aManger BOOLEAN,
    partie_id INTEGER,
    FOREIGN KEY (partie_id) REFERENCES partie(partie_id) ON DELETE CASCADE,
    FOREIGN KEY (tdj_joueurActif) REFERENCES joueur(joueur_id) ON DELETE CASCADE
);

CREATE TABLE salon (
    partie_id INTEGER PRIMARY KEY,
    joueur1 INTEGER,
    joueur2 INTEGER,
    FOREIGN KEY (partie_id) REFERENCES partie(partie_id) ON DELETE CASCADE,
    FOREIGN KEY (joueur1) REFERENCES joueur(joueur_id) ON DELETE CASCADE,
    FOREIGN KEY (joueur2) REFERENCES joueur(joueur_id) ON DELETE CASCADE
);

CREATE TABLE tourdejeu (
    tdj_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tdj_nTour INTEGER NOT NULL,
    tdj_joueurActif INTEGER NOT NULL,
    xDepart INTEGER NOT NULL,
    yDepart INTEGER NOT NULL,
    xArrive INTEGER NOT NULL,
    yArrive INTEGER NOT NULL,
    tdj_aManger BOOLEAN,
    partie_id INTEGER,
    FOREIGN KEY (partie_id) REFERENCES partie(partie_id) ON DELETE CASCADE,
    FOREIGN KEY (tdj_joueurActif) REFERENCES joueur(joueur_id) ON DELETE CASCADE
);

CREATE TABLE codes_attente (
    code INTEGER PRIMARY KEY,
    user_id INTEGER NOT NULL,
    username VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_public BOOLEAN DEFAULT TRUE
);

CREATE INDEX idx_codes_attente_created ON codes_attente(created_at);

CREATE TABLE rematch_invitations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code INTEGER NOT NULL UNIQUE,
    old_partie_code INTEGER NOT NULL,
    host_user_id INTEGER NOT NULL,
    invited_user_id INTEGER NOT NULL,
    host_username VARCHAR(255) NOT NULL,
    invited_username VARCHAR(255) NOT NULL,
    status VARCHAR(15) NOT NULL DEFAULT 'EN ATTENTE'
        CHECK (status IN ('EN ATTENTE', 'ACCEPTER', 'REFUSER')),
    created_at TIMESTAMP NOT NULL,
    accepted_at TIMESTAMP,
    refused_at TIMESTAMP,
    FOREIGN KEY (host_user_id) REFERENCES users(users_id) ON DELETE CASCADE,
    FOREIGN KEY (invited_user_id) REFERENCES users(users_id) ON DELETE CASCADE
);

CREATE INDEX idx_rematch_host_user ON rematch_invitations(host_user_id);
CREATE INDEX idx_rematch_invited_user ON rematch_invitations(invited_user_id);
CREATE INDEX idx_rematch_status ON rematch_invitations(status);
CREATE INDEX idx_rematch_status_invited ON rematch_invitations(status, invited_user_id);
CREATE INDEX idx_rematch_created_at ON rematch_invitations(created_at);